#!/bin/bash -x
#BSUB -P APH114
#BSUB -J libE_fbpic
#BSUB -W 00:30
#BSUB -nnodes 2
#BSUB -alloc_flags "smt1"

module purge
module load gcc/4.8.5
module load cuda/9.1.85
module load spectrum-mpi/10.3.1.2-20200121
module load fftw/3.3.8
module load python/3.7.0-anaconda3-5.3.0
source activate fbpic
export CUPY_CACHE_DIR=/gpfs/alpine/scratch/rlehe/aph114/.cupy/kernel_cache

export NUMBA_NUM_THREADS=1
export OMP_NUM_THREADS=1
export FBPIC_ENABLE_GPUDIRECT=0
export FBPIC_DISABLE_CACHING=1

# Script to run libEnsemble using multiprocessing on launch nodes.
# Assumes Conda environment is set up.

# To be run with central job management
# - Manager and workers run on launch node.
# - Workers submit tasks to the nodes in the job available.

python run_libensemble.py --comms local --nworkers 12
