#!/bin/bash -x
#SBATCH -J libE_test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time=24:00:00
#SBATCH --partition=maxgpu,allgpu
#SBATCH --constraint=V100|P100

source activate optimization

export NUMBA_NUM_THREADS=1
export OMP_NUM_THREADS=1
export FBPIC_ENABLE_GPUDIRECT=0

# Script to run libEnsemble using multiprocessing on launch nodes.
# Assumes Conda environment is set up.

export LIBE_SIM_EXTRA_ARGS="--gres=gpu:1"

python run_libensemble.py --comms local --nworkers 3
