#!/bin/bash -x
#SBATCH -J {name}
#SBATCH --nodes={n_nodes}
#SBATCH --ntasks-per-node=4
#SBATCH --output=mpi-out.%j
#SBATCH --error=mpi-err.%j
#SBATCH --time={max_time}
#SBATCH --partition=maxgpu,allgpu
#SBATCH --constraint=V100|P100

source activate optimization

export NUMBA_NUM_THREADS=1
export OMP_NUM_THREADS=1
export FBPIC_ENABLE_GPUDIRECT=0

# Script to run libEnsemble using multiprocessing on launch nodes.
# Assumes Conda environment is set up.

export LIBE_SIM_EXTRA_ARGS="--gres=gpu:1"

python run_example.py --comms local --nworkers {n_workers}
