#!/bin/bash -x
#BSUB -P APH114
#BSUB -J {name}
#BSUB -W {max_time}
#BSUB -nnodes {n_nodes}
#BSUB -alloc_flags "smt1"

module purge
module load gcc/4.8.5
module load cuda/9.1.85
module load spectrum-mpi/10.3.1.2-20200121
module load fftw/3.3.8
module load python/3.7.0-anaconda3-5.3.0
source activate fbpic
export CUPY_CACHE_DIR=/gpfs/alpine/scratch/rlehe/aph114/.cupy/kernel_cache

export NUMBA_NUM_THREADS=1
export OMP_NUM_THREADS=1
export FBPIC_ENABLE_GPUDIRECT=0
export FBPIC_DISABLE_CACHING=1

# Script to run libEnsemble using multiprocessing on launch nodes.
# Assumes Conda environment is set up.

export LIBE_GPUS_PER_SIM=1
export LIBE_SIM_EXTRA_ARGS="-a 1 -g 1 -c 1 --bind=packed:1"

python run_example.py --comms local --nworkers {n_workers}
